<%@ Page Title="" Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="Home.aspx.vb" Inherits="Default3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style137 {
            width: 75%;
            margin-left: 72px;
        }
        .auto-style138 {
            width: 992px;
        }
    .auto-style139 {
        font-size: medium;
    }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <table class="auto-style137" style="opacity:0.8; font-weight :bold ;">
        <tr style ="border-bottom :solid; border-width : 1px">
            <td class="auto-style138">
                <h2 class="page_heading" style="box-sizing: border-box; margin: 0px 0px 5px; font-family: Arial, sans-serif; font-weight: normal; line-height: 1.1; color: rgb(6, 131, 196); font-size: 20px; border-bottom: 1px solid rgb(222, 222, 222); padding: 10px 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Salient Features of JoSAA</h2>
            </td>
        </tr>
        <tr>
            <td class="auto-style138">&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style138">
                <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">
                    The&nbsp;<b style="box-sizing: border-box; margin: 0px; font-weight: bold;">Joint Seat Allocation Authority (JoSAA) 2018</b><span style="box-sizing: border-box; margin: 0px">&nbsp;</span>has been set up by the Ministry of Human Resources Development (MHRD) to manage and regulate the joint seat allocation for admissions to 100 institutes for the academic year 2018-19. This includes 23 IITs,&nbsp; 31 NITs, 23 IIITs and 23 Other-Government Funded Technical Institutes (Other-GFTIs). Admission to all the academic programs offered by these Institutes will be made through a single platform.<span style="box-sizing: border-box; margin: 0px;"><br style="box-sizing: border-box; margin: 0px;" />
                    <br style="box-sizing: border-box; margin: 0px;" />
                    <b style="box-sizing: border-box; margin: 0px; font-weight: bold;">All the candidates</b>&nbsp;</span>who appeared for<b style="box-sizing: border-box; margin: 0px; font-weight: bold;"><span style="box-sizing: border-box; margin: 0px;">&nbsp;</span>JEE (Main) 2018 / JEE (Advanced) 2018 should take note of the following important points:</b><span style="box-sizing: border-box; margin: 0px;"><br style="box-sizing: border-box; margin: 0px;" />
                    <br style="box-sizing: border-box; margin: 0px;" />
                    <o:p style="box-sizing: border-box; margin: 0px;"></o:p></span>
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Registration</b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">:</span><o:p style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></o:p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">All candidates who have appeared in&nbsp;</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139"><span style="box-sizing: border-box; margin: 0px;">JEE 
                (Main) 2018</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span class="auto-style139">&nbsp;</span></span><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">are eligible to register for seat allocation in NIT+ system (except IITs).</span><o:p style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></o:p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">All candidates who have declared qualified in&nbsp;</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139"><span style="box-sizing: border-box; margin: 0px;">JEE 
                (Adv) 2018</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span class="auto-style139">&nbsp;</span></span><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">are eligible to register for seat allocation in all participating Institutes.</span><o:p style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></o:p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139"><span style="box-sizing: border-box; margin: 0px;">Filling-in of choices</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">: 
                Candidates may fill-in their choices of Institutes and branches in decreasing order of their preference. Candidates are strongly urged to fill-in as many choices of their interest as possible.</span><o:p style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></o:p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Locking of choices:<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">Candidates 
                MUST “lock” their choices. For candidates who do NOT lock their choices, their last saved choices will be locked automatically when the time-window for filling-in of choices closes.</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><o:p style="box-sizing: border-box; margin: 0px;"></o:p></b><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Number of rounds of seat allocation:<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">JoSAA 
                will conduct seven rounds that is 1st through 7th rounds of seat allocation for academic programs offered by Institutes under JoSAA 2018.</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><o:p style="box-sizing: border-box; margin: 0px;"></o:p></b><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Seat acceptance:<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">Candidates 
                allotted a seat must pay the seat acceptance fee (through SBI e-Challan/SBI NetBanking/SBI debit cards) and get the documents verified at any reporting center (josaa.nic.in) for provisional seat acceptance .</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><o:p style="box-sizing: border-box; margin: 0px;"></o:p></b><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Participation in subsequent rounds:<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">A 
                candidate is required to fill option for ‘freeze’, ‘slide’ or ‘float’ the choice of academic program.</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><o:p style="box-sizing: border-box; margin: 0px;"></o:p></b><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Dual Reporting:<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">If 
                in a subsequent round, a candidate’s allotment from NIT+ system changes to an IIT, the candidate MUST report ONCE AGAIN at an IIT reporting centre, similarly if a candidate’s allotment from IIT changes to an NIT+ system, the candidate MUST report ONCE AGAIN at any NIT+ reporting centre, failure to do so will result in forfeiture of seats allocated in both NIT+ system and IIT.&nbsp;</span><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139"><span style="box-sizing: border-box; margin: 0px;">Withdraw option</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">: 
                A candidate, who has already accepted a seat, can withdraw the seat by reporting at a reporting center up to sixth round of seat allocation.</span><br style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139" />
                <br style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139" />
                <o:p style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></o:p>
                <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139"><i style="box-sizing: border-box; margin: 0px;"><u style="box-sizing: border-box; margin: 0px;">Important:&nbsp;</u></i></b><o:p style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></o:p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Registration&nbsp;–<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">Candidates 
                who do NOT register within the specified time window WILL NOT be able to seek admission for this academic year.</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><o:p style="box-sizing: border-box; margin: 0px;"></o:p></b><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Filling-in of choices&nbsp;–<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">Candidates 
                who do NOT fill-in choices within the specified time window WILL NOT be able to seek admission for this academic year</span><b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><o:p style="box-sizing: border-box; margin: 0px;"></o:p></b><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139">Dual Reporting:<span>&nbsp;</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">Two 
                times reporting required in case of seat allotment changes from NIT+s system to IITs and vice versa.&nbsp;</span><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <b style="box-sizing: border-box; margin: 0px; font-weight: bold; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" class="auto-style139"><span style="box-sizing: border-box; margin: 0px;">No modification of locked choices</span></b><span style="color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style139">&nbsp;– 
                once locked, choices CANNOT be modified.</span><o:p style="box-sizing: border-box; margin: 0px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></o:p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                </p>
                <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(118, 118, 118); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                    <span class="auto-style139">For complete details, please visit http://josaa.nic.in and</span><span "times=" arial","sans-serif";mso-fareast-font-family:="" new="" roman";color:#0000cc"="" style="box-sizing: border-box; margin: 0px; line-height: 15.3333px;"><span class="auto-style139">&nbsp;</span></span><span "times=" arial","sans-serif";mso-fareast-font-family:="" new="" roman";color:#0000cc"="" style="box-sizing: border-box; margin: 0px; line-height: 15.3333px;" class="auto-style139">MUST</span><span "times=" arial","sans-serif";mso-fareast-font-family:="" new="" roman";color:#0000cc"="" style="box-sizing: border-box; margin: 0px; font-size: 10pt; line-height: 15.3333px;"><span arial","sans-serif";mso-fareast-font-family:"times="" new="" roman";color:#660066"="" style="box-sizing: border-box; margin: 0px; line-height: 15.3333px;"><span "times=" arial","sans-serif";mso-fareast-font-family:="" new="" roman";color:#0000cc"="" style="box-sizing: border-box; margin: 0px; line-height: 15.3333px;"><span class="auto-style139">&nbsp;</span></span></span><span "times=" arial","sans-serif";mso-fareast-font-family:="" new="" roman";color:#0000cc"="" style="box-sizing: border-box; margin: 0px; line-height: 15.3333px;"><span arial","sans-serif";mso-fareast-font-family:"times="" new="" roman";color:#660066"="" style="box-sizing: border-box; margin: 0px; line-height: 15.3333px;" class="auto-style139">read<span>&nbsp;</span>BUSINESS RULE.</span></span></span></p>
            </td>
        </tr>
    </table>
</asp:Content>






